package com.example.ui.components

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

enum class AppLanguage(val code: String, val displayName: String) {
    UZ_LATIN("uz_lat", "O'zbekcha (Lotin)"),
    UZ_CYRILLIC("uz_cyr", "Ўзбекча (Крил)"),
    KAZAKH("kk", "Qazaqsha / Қазақша"),
    KYRGYZ("ky", "Кыргызча / Кыргыз"),
    RUSSIAN("ru", "Русский"),
    KARAKALPAK("kaa", "Qaraqalpaqsha"),
    ENGLISH("en", "English")
}

object Localization {
    private val translations = mapOf(
        AppLanguage.UZ_LATIN to mapOf(
            "app_name" to "Qalqon",
            "dashboard" to "Me'yor",
            "protection" to "SMS/Aloqa",
            "monitoring" to "Veb-Filtr",
            "apk_scan" to "Skaner",
            "settings" to "Sozlamalar",
            "system_protected" to "TIZIM HIMOYALANGAN",
            "security_mode" to "XAVFSIZLIK REJIMI",
            "inactive" to "FAOLMAS",
            "spam_block" to "SPAM BLOK",
            "web_filter" to "VEB FILTR",
            "spam_desc" to "Taqiqlangan qo'ng'iroq/sms",
            "domains_desc" to "Bloklangan domenlar",
            "bg_active" to "Fon rejimi faol va himoyada",
            "bg_inactive" to "Himoya o'chirilgan",
            "recent_activity" to "OXIRGI FAQOLIYAT JURNALI",
            "view_all" to "Barchasi >",
            "no_logs" to "Hozircha bloklash jurnallari mavjud emas.",
            "sms_call_title" to "QALQON FILTRI",
            "sms_call_sub" to "SMS va telefon spam qo'ng'iroqlarini boshqarish",
            "add_spam_num" to "Spam Raqam Qo'shish",
            "phone_num" to "Telefon raqam",
            "num_placeholder" to "Masalan, +998901234567",
            "label_name" to "Yorliq / Nom",
            "label_placeholder" to "Masalan, Qallob / Spam",
            "save" to "Saqlash",
            "cancel" to "Bekor qilish",
            "blacklist_web" to "QORALIST VEB-FILTR",
            "parental_control" to "Parental-control: Taqiqlangan saytlarga kirishni cheklash",
            "add_domain_title" to "Taqiqlangan Domen Qo'shish",
            "add_domain_desc" to "Masalan: betting-link.uz. Ilova subdomenlarni ham avtomatik bloklaydi.",
            "domain_address" to "Domen manzili",
            "block_reason" to "Bloklash sababi",
            "block" to "Bloklash",
            "domain_list_empty" to "Bloklangan saytlar mavjud emas.",
            "domain_list_title" to "BLOKLANGAN DOMENLAR RO'YXATI",
            "danger_desc" to "Barcha o'rnatilgan paketlarni tahlil qiling. Tizim maxfiylik ruxsatlarini skanerlaydi.",
            "danger_scanner" to "XAVFLI PROGRAMMALAR SKANERI",
            "admin_settings" to "MA'MURIY SOZLAMALAR",
            "pin_code" to "PIN Kod",
            "wrong_pin" to "PIN kod xato!",
            "success_login" to "Muvaffaqiyatli kirildi!",
            "admin_locked" to "Administrator Bo'limi Qulflangan",
            "admin_locked_desc" to "O'zgarishlar kiritish uchun administrator PIN-kodini kiriting.",
            "enter" to "KIRISH",
            "change_pin" to "PIN Kodni o'zgartirish",
            "old_pin" to "Eski PIN",
            "new_pin" to "Yangi PIN",
            "confirm_pin" to "Tasdiqlang",
            "pin_update_btn" to "PAROLNI YANGILASH",
            "clear_db" to "Ma'lumotlar bazasini tozalash",
            "clear_db_desc" to "Ushbu tugma bosilganda spam ro'yxati va daxldor veb filtrlar o'chirilib zavod holatiga qaytariladi.",
            "clear_db_btn" to "MA'LUMOTLARNI TOZALASH (RESET)",
            "theme_setting" to "🎨 INTERFEYS MAVZUSI (KUN / TUN)",
            "theme_desc" to "Ilovani oq (kunduzgi) yoki qora (tungi) rejimda ishlatish uchun quyidagi tugmani bosing.",
            "light_mode_label" to "KUNDUZGI (OQ) REJIM",
            "dark_mode_label" to "TUNGI (QORA) REJIM",
            "device_info" to "📱 QURILMA MA'LUMOTLARI",
            "system_label" to "Tizim:",
            "access_desc" to "Brauzer filtri",
            "access_on" to "Xizmat faol holatda",
            "access_off" to "Maxsus ruxsat berilmagan",
            "enable" to "Yoqish",
            "fix" to "Tuzatish",
            "guide_toggle_show" to "+ Faollashtirish bo'yicha yo'riqnomani ochish",
            "guide_toggle_hide" to "- Faollashtirish bo'yicha yo'riqnomani berkitish",
            "guide_title" to "🌐 BRAUZER FILTRINI FAOL QILISH YO'RIG'NOMASI",
            "guide_step_title" to "Google Chrome va boshqa brauzerlarda taqiqlangan saytlarni aniqlash uchun quyidagi qadamlarni bajaring:",
            "guide_step_1" to "Tepa o'ng qatordagi 'Yoqish' tugmasini bosing (Tizim accessibility sozlamalari ochiladi).",
            "guide_step_2" to "U yerdan 'Yuklab olingan xizmatlar' (Downloaded Services) yoki 'O'rnatilgan xizmatlar' (Installed Apps) bandini toping.",
            "guide_step_3" to "U yerdan 'Qalqon' xizmatiga bosib, uni faollashtiring (Yoqish / ON).",
            "guide_warn" to "💡 Diqqat: Bu ruxsatnoma orqali ilova faqat siz kiritgan blok-domenlarni tekshiradi va hech qanday shaxsiy ma'lumotlarni yig'maydi.",
            "add_new_domain" to "Yangi Domen Bloklash",
            "add_domain_sub" to "Sayt yoki o'yin guruhlari linklarini bloklash",
            "add_btn" to "Kiritish",
            "spam_list" to "KIRITILGAN SPAM RAQAMLAR",
            "spam_list_empty" to "Raqamlar ro'yxati bo'sh.",
            "add_spam_btn" to "Raqamni bloklash",
            "import_txt" to "TXT fayldan import qilish",
            "url_sync" to "URL manzildan sinxronlash",
            "keywords" to "Kalit so'zlar orqali filtrlash",
            "keywords_desc" to "Har bir qatorda bittadan kalit so'z kiritasiz (masalan stavka, 1xbet)",
            "add_keyword" to "Kalit so'z qo'shish",
            "keyword" to "Kalit so'z",
            "registered_keywords" to "KIRITILGAN KALIT SO'ZLAR",
            "admin_only_overlay" to "Ushbu bo'lim faqat Administrator uchun! Sozlamalardan 'Administrator Bo'limi'ni faollashtiring.",
            "select_language" to "🇺🇿 ILOWA TILI (LANGUAGE)"
        ),
        AppLanguage.UZ_CYRILLIC to mapOf(
            "app_name" to "Қалқон",
            "dashboard" to "Меёр",
            "protection" to "SMS/Алоқа",
            "monitoring" to "Веб-Фильтр",
            "apk_scan" to "Сканер",
            "settings" to "Созламалар",
            "system_protected" to "ТИЗИМ ҲИМОЯЛАГАН",
            "security_mode" to "ХАВФСИЗЛИК РЕЖИМИ",
            "inactive" to "ФАОЛМАС",
            "spam_block" to "СПАМ БЛОК",
            "web_filter" to "ВЕБ ФИЛЬТР",
            "spam_desc" to "Тақиқланган қўнғироқ/смс",
            "domains_desc" to "Блокланган доменлар",
            "bg_active" to "Фон режими фаол ва ҳимояда",
            "bg_inactive" to "Ҳимоя ўчирилган",
            "recent_activity" to "ОХИРГИ ФАОЛИЯТ ЖУРНАЛИ",
            "view_all" to "Барчаси >",
            "no_logs" to "Ҳозирча блоклаш журналлари мавжуд эмас.",
            "sms_call_title" to "ҚАЛҚОН ФИЛЬТРИ",
            "sms_call_sub" to "SMS ва телефон спам қўнғироқларини бошқариш",
            "add_spam_num" to "Спам Рақам Қўшиш",
            "phone_num" to "Телефон рақам",
            "num_placeholder" to "Масалан, +998901234567",
            "label_name" to "Ёрлиқ / Ном",
            "label_placeholder" to "Масалан, Қаллоб / Спам",
            "save" to "Сақлаш",
            "cancel" to "Бекор қилиш",
            "blacklist_web" to "ҚОРАЛИСТ ВЕБ-ФИЛЬТР",
            "parental_control" to "Parental-control: Тақиқланган сайтларга киришни чеклаш",
            "add_domain_title" to "Тақиқланган Домен Қўшиш",
            "add_domain_desc" to "Масалан: betting-link.uz. Илова субдоменларни ҳам автоматик блоклайди.",
            "domain_address" to "Домен манзили",
            "block_reason" to "Блоклаш сабаби",
            "block" to "Блоклаш",
            "domain_list_empty" to "Блокланган сайтлар мавжуд эмас.",
            "domain_list_title" to "БЛОКЛАНГАН ДОМЕНЛАР РОЎХАТИ",
            "danger_desc" to "Барча ўрнатилган пакетларни таҳлил қилинг. Тизим махфийлик рухсатларини сканерлайди.",
            "danger_scanner" to "ХАВФЛИ ПРОГРАММАЛАР СКАНЕРИ",
            "admin_settings" to "МАЪМУРИЙ СОЗЛАМАЛАР",
            "pin_code" to "PIN Код",
            "wrong_pin" to "PIN код хато!",
            "success_login" to "Муваффақиятли кирилди!",
            "admin_locked" to "Администратор Бўлими Қуфланган",
            "admin_locked_desc" to "Ўзгаришлар киритиш учун администратор PIN-кодини киритинг.",
            "enter" to "КИРИШ",
            "change_pin" to "PIN Кодни ўзгартириш",
            "old_pin" to "Ески PIN",
            "new_pin" to "Янги PIN",
            "confirm_pin" to "Тасдиқланг",
            "pin_update_btn" to "ПАРОЛНИ ЯНГИЛАШ",
            "clear_db" to "Маълумотлар базасини тозалаш",
            "clear_db_desc" to "Ушбу тугма босилганда спам рўйхати ва дахлдор веб фильтрлар ўчирилиб завод ҳолатига қайтарилади.",
            "clear_db_btn" to "МАЪЛУМОТЛАРНИ ТОЗАЛАШ (RESET)",
            "theme_setting" to "🎨 ИНТЕРФЕЙС МАВЗУСИ (КУН / ТУН)",
            "theme_desc" to "Иловани оқ (кундузги) ёки қора (тунги) режимда ишлатиш учун қуйидаги тугмани босинг.",
            "light_mode_label" to "КУНДУЗГИ (ОҚ) РЕЖИМ",
            "dark_mode_label" to "ТУНГИ (ҚОРА) РЕЖИМ",
            "device_info" to "📱 ҚУРИЛМА МАЪЛУМОТЛАРИ",
            "system_label" to "Тизим:",
            "access_desc" to "Браузер фильтри",
            "access_on" to "Хизмат фаол ҳолатда",
            "access_off" to "Махсус рухсат берилмаган",
            "enable" to "Ёқиш",
            "fix" to "Тузатиш",
            "guide_toggle_show" to "+ Фаоллаштириш бўйича йўриқномани очиш",
            "guide_toggle_hide" to "- Фаоллаштириш бўйича йўриқномани беркитиш",
            "guide_title" to "🌐 БРАУЗЕР ФИЛЬТРИНИ ФАОЛ ҚИЛИШ ЙЎРИҚНОМАСИ",
            "guide_step_title" to "Google Chrome ва бошқа браузерларда тақиқланган сайтларни аниқлаш учун қуйидаги қадамларни бажаринг:",
            "guide_step_1" to "Теппа ўнг қатордаги 'Ёқиш' тугмасини босинг (Тизим аccессибилитй созламалари очилади).",
            "guide_step_2" to "У ердан 'Юклаб олинган хизматлар' (Доўнлоадед Сервицес) ёки 'Ўрнатилган хизматлар' (Инсталлед Аппс) бандини топинг.",
            "guide_step_3" to "У ердан 'Қалқон' хизматига босиб, уни фаоллаштиринг (Ёқиш / ОН).",
            "guide_warn" to "💡 Диққат: Бу рухсатнома орқали илова фақат сиз киритган блок-доменларни текширади ва ҳеч қандай шахсий маълумотларни йиғмайди.",
            "add_new_domain" to "Янги Домен Блоклаш",
            "add_domain_sub" to "Сайт ёки ўйин гуруҳлари линкларини блоклаш",
            "add_btn" to "Киритиш",
            "spam_list" to "КИРИТИЛГАН СПАМ РАҚАМЛАР",
            "spam_list_empty" to "Рақамлар рўйхати бўш.",
            "add_spam_btn" to "Рақамни блоклаш",
            "import_txt" to "TXT файлдан импорт қилиш",
            "url_sync" to "URL манзилдан синхронлаш",
            "keywords" to "Калит сўзлар орқали филтрлаш",
            "keywords_desc" to "Ҳар бир қаторда биттадан калит сўз киритасиз (масалан ставка, 1xbet)",
            "add_keyword" to "Калит сўз қўшиш",
            "keyword" to "Калит сўз",
            "registered_keywords" to "КИРИТИЛГАН КАЛИТ СЎЗЛАР",
            "admin_only_overlay" to "Ушбу бўлим фақат Администратор учун! Созламалардан 'Администратор Бўлими'ни фаоллаштиринг.",
            "select_language" to "🇺🇿 ИЛОВА ТИЛИ (LANGUAGE)"
        ),
        AppLanguage.KAZAKH to mapOf(
            "app_name" to "Qalqon",
            "dashboard" to "Басты",
            "protection" to "SMS/Қоңырау",
            "monitoring" to "Веб-Фильтр",
            "apk_scan" to "Сканер",
            "settings" to "Баптаулар",
            "system_protected" to "ЖҮЙЕ ҚОРҒАЛҒАН",
            "security_mode" to "ҚАУІПСІЗДІК РЕЖИМІ",
            "inactive" to "БЕЛСЕНДІ ЕМЕС",
            "spam_block" to "СПАМ БЛОК",
            "web_filter" to "ВЕБ ФИЛЬТР",
            "spam_desc" to "Тыйым салынған қоңырау/sms",
            "domains_desc" to "Блокталған домендер",
            "bg_active" to "Фондық режим белсенді және қорғауда",
            "bg_inactive" to "Қорғаныс өшірілген",
            "recent_activity" to "СОҢҒЫ ӘРЕКЕТТЕР ТІЗІМІ",
            "view_all" to "Барлығы >",
            "no_logs" to "Бұғаттау журналдары әлі жоқ.",
            "sms_call_title" to "QALQON ФИЛЬТРІ",
            "sms_call_sub" to "SMS және телефон спам қоңырауларын басқару",
            "add_spam_num" to "Спам Нөмір Қосу",
            "phone_num" to "Телефон нөмірі",
            "num_placeholder" to "Мысалы, +998901234567",
            "label_name" to "Атауы / Белгі",
            "label_placeholder" to "Мысалы, Алаяқ / Спам",
            "save" to "Сақтау",
            "cancel" to "Бас тарту",
            "blacklist_web" to "ҚАРА ТІЗІМ ВЕБ-ФИЛЬТР",
            "parental_control" to "Ата-ана бақылауы: Тыйым салынған сайттарды шектеу",
            "add_domain_title" to "Тыйым Салынған Домен Қосу",
            "add_domain_desc" to "Мысалы: betting-link.uz. Қосымша субдомендерді де автоматты түрде бұғаттайды.",
            "domain_address" to "Домен мекенжайы",
            "block_reason" to "Бұғаттау себебі",
            "block" to "Бұғаттау",
            "domain_list_empty" to "Бұғатталған сайттар жоқ.",
            "domain_list_title" to "БҰҒАТТАЛҒАН ДОМЕНДЕР ТІЗІМІ",
            "danger_desc" to "Барлық орнатылған пакеттерді талдаңыз. Жүйе құпиялылық рұқсаттарын тексереді.",
            "danger_scanner" to "ҚАУІПТІ БАҒДАРЛАМАЛАР СКАНЕРІ",
            "admin_settings" to "ӘКІМШІЛІК РЕТТЕУЛЕР",
            "pin_code" to "PIN Код",
            "wrong_pin" to "PIN код қате!",
            "success_login" to "Сәтті кірдіңіз!",
            "admin_locked" to "Әкімші Бөлімі Бұғатталған",
            "admin_locked_desc" to "Өзгерістер енгізу үшін әкімші PIN-кодын енгізіңіз.",
            "enter" to "КІРУ",
            "change_pin" to "PIN Кодты өзгерту",
            "old_pin" to "Ескі PIN",
            "new_pin" to "Жаңа PIN",
            "confirm_pin" to "Растаңыз",
            "pin_update_btn" to "ҚҰПИЯ СӨЗДІ ЖАҢАРТУ",
            "clear_db" to "Деректер базасын тазалау",
            "clear_db_desc" to "Бұл батырма басылғанда спам тізімі мен веб-фильтрлер өшіріліп, зауыттық күйге қайтарылады.",
            "clear_db_btn" to "ДЕРЕКТЕРДІ ТАЗАЛАУ (RESET)",
            "theme_setting" to "🎨 ИНТЕРФЕЙС ТАҚЫРЫБЫ (КҮН / ТҮН)",
            "theme_desc" to "Қосымшаны ақ (күндізгі) немесе қара (түнгі) режимде пайдалану үшін төмендегі батырманы басыңыз.",
            "light_mode_label" to "КҮНДІЗГІ (АҚ) РЕЖИМ",
            "dark_mode_label" to "ТҮНГІ (ҚАРА) РЕЖИМ",
            "device_info" to "📱 ҚҰРЫЛҒЫ МӘЛІМЕТТЕРІ",
            "system_label" to "Жүйе:",
            "access_desc" to "Браузер фильтрі",
            "access_on" to "Қызмет белсенді",
            "access_off" to "Арнайы рұқсат берілмеген",
            "enable" to "Қосу",
            "fix" to "Түзету",
            "guide_toggle_show" to "+ Белсендіру нұсқаулығын ашу",
            "guide_toggle_hide" to "- Белсендіру нұсқаулығын жабу",
            "guide_title" to "🌐 БРАУЗЕР ФИЛЬТРІН ІСКЕ ҚОСУ НҰСҚАУЛЫҒЫ",
            "guide_step_title" to "Google Chrome және басқа браузерлерде тыйым салынған сайттарды анықтау үшін келесі әрекеттерді орындаңыз:",
            "guide_step_1" to "Жоғарғы оң жақтағы 'Қосу' батырмасын басыңыз (Арнайы мүмкіндіктер баптаулары ашылады).",
            "guide_step_2" to "Одан 'Жүктелген қызметтер' немесе 'Орнатылған бағдарламалар' бөлімін табыңыз.",
            "guide_step_3" to "Содан кейін 'Qalqon' қызметін тауып, оны қосыңыз (ON).",
            "guide_warn" to "💡 Назар аударыңыз: Бұл рұқсат арқылы қосымша тек сіз енгізген бұғатталған домендерді тексереді және ешқандай жеке деректерді жинамайды. ",
            "add_new_domain" to "Жаңа Доменді Бұғаттау",
            "add_domain_sub" to "Сайт немесе ойын топтарының сілтемелерін бұғаттау",
            "add_btn" to "Енгізу",
            "spam_list" to "ЕНГІЗІЛГЕН СПАМ НӨМІРЛЕР",
            "spam_list_empty" to "Нөмірлер тізімі бос.",
            "add_spam_btn" to "Нөмірді бұғаттау",
            "import_txt" to "TXT файлдан импорттау",
            "url_sync" to "URL мекенжайынан синхрондау",
            "keywords" to "Кілт сөздер арқылы сүзгілеу",
            "keywords_desc" to "Әр жолға бір кілт сөзді енгізесіз (мысалы stavka, 1xbet)",
            "add_keyword" to "Кілт сөзді қосу",
            "keyword" to "Кілт сөз",
            "registered_keywords" to "ЕНГІЗІЛГЕН КІЛТ СӨЗДЕР",
            "admin_only_overlay" to "Бұл бөлім тек Әкімшіге арналған! Баптаулардан 'Әкімші Бөлімін' белсендіріңіз.",
            "select_language" to "🇺🇿 ТІЛ БАПТАУЛАРЫ (LANGUAGE)"
        ),
        AppLanguage.KYRGYZ to mapOf(
            "app_name" to "Qalqon",
            "dashboard" to "Башкы",
            "protection" to "SMS/Чалуу",
            "monitoring" to "Веб-Фильтр",
            "apk_scan" to "Сканер",
            "settings" to "Жөндөөлөр",
            "system_protected" to "ТУТУМ КОРГОЛГОН",
            "security_mode" to "КООПСУЗДУК РЕЖИМИ",
            "inactive" to "АКТИВДҮҮ ЭМЕС",
            "spam_block" to "СПАМ БЛОК",
            "web_filter" to "ВЕБ ФИЛЬТР",
            "spam_desc" to "Тыюу салынган чалуу/sms",
            "domains_desc" to "Бөгөттөлгөн домендер",
            "bg_active" to "Фондук режим активдүү жана коргоодо",
            "bg_inactive" to "Коргоо өчүрүлгөн",
            "recent_activity" to "АКЫРКЫ АРАКЕТТЕР ТИЗМЕГИ",
            "view_all" to "Бардыгы >",
            "no_logs" to "Бөгөттөө журналдары боло элек.",
            "sms_call_title" to "QALQON ФИЛЬТРИ",
            "sms_call_sub" to "SMS жана телефон спам чалууларын башкаруу",
            "add_spam_num" to "Спам Номер Кошуу",
            "phone_num" to "Телефон номери",
            "num_placeholder" to "Мисалы, +998901234567",
            "label_name" to "Белги / Аты",
            "label_placeholder" to "Мисалы, Шүмдүк / Спам",
            "save" to "Сактоо",
            "cancel" to "Жокко чыгаруу",
            "blacklist_web" to "КАРА ТИЗМЕ ВЕБ-ФИЛЬТР",
            "parental_control" to "Ата-эне көзөмөлү: Тыюу салынган сайттарды чектөө",
            "add_domain_title" to "Тыюу Салынган Домен Кошуу",
            "add_domain_desc" to "Мисалы: betting-link.uz. Колдонмо субдомендерди да автоматтык түрдө бөгөттөйт.",
            "domain_address" to "Домен дареги",
            "block_reason" to "Бөгөттөө себеби",
            "block" to "Бөгөттөө",
            "domain_list_empty" to "Бөгөттөлгөн сайттар жок.",
            "domain_list_title" to "БӨГӨТТӨЛГӨН ДОМЕНДЕР ТИЗМЕГИ",
            "danger_desc" to "Бардык орнотулган пакеттерди талдаңыз. Тутум купуялык уруксаттарын текшерет.",
            "danger_scanner" to "КООПТУУ ПРОГРАММАЛАР СКАНЕРИ",
            "admin_settings" to "АДМИНИСТРАТИВДИК ЖӨНДӨӨЛӨР",
            "pin_code" to "PIN Код",
            "wrong_pin" to "PIN код ката!",
            "success_login" to "Ийгиликтүү кирдиңиз!",
            "admin_locked" to "Администратор Бөлүмү Кулпуланган",
            "admin_locked_desc" to "Өзгөрүүлөрдү киргизүү үчүн администратор PIN-кодун киргизиңиз.",
            "enter" to "КИРҮҮ",
            "change_pin" to "PIN Кодду өзгөртүү",
            "old_pin" to "Эски PIN",
            "new_pin" to "Жаңы PIN",
            "confirm_pin" to "Ырастаңыз",
            "pin_update_btn" to "СЫР СӨЗДҮ ЖАҢЫЛОО",
            "clear_db" to "Маалыматтар базасын тазалоо",
            "clear_db_desc" to "Бул баскыч басылганда спам тизмеси жана веб-фильтрлер өчүрүлүп заводдук абалга кайтарылат.",
            "clear_db_btn" to "МААЛЫМАТТАРДЫ ТАЗАЛОО (RESET)",
            "theme_setting" to "🎨 ИНТЕРФЕЙС ТЕМАСЫ (КҮН / ТҮН)",
            "theme_desc" to "Тиркемени ак (күндүзгү) же кара (түнкү) режимде колдонуу үчүн төмөнкү баскычты басыңыз.",
            "light_mode_label" to "КҮНДҮЗГҮ (АК) РЕЖИМ",
            "dark_mode_label" to "ТҮНКҮ (КАРА) РЕЖИМ",
            "device_info" to "📱 ТҮЗҮЛҮШ ЖӨНҮНДӨ МААЛЫМАТ",
            "system_label" to "Тутум:",
            "access_desc" to "Браузер фильтри",
            "access_on" to "Кызмат активдүү",
            "access_off" to "Атайын уруксат берилген эмес",
            "enable" to "Күйгүзүү",
            "fix" to "Оңдоо",
            "guide_toggle_show" to "+ Активдештирүү көрсөтмөсүн ачуу",
            "guide_toggle_hide" to "- Активдештирүү көрсөтмөсүн жабуу",
            "guide_title" to "🌐 БРАУЗЕР ФИЛЬТРИН ИШКЕ КИРГИЗҮҮ КӨРСӨТМӨСҮ",
            "guide_step_title" to "Google Chrome жана башка браузерлерде тыюу салынган сайттарды аныктоо үчүн төмөнкү кадамдарды аткарыңыз:",
            "guide_step_1" to "Жогору оң жактагы 'Күйгүзүү' баскычын басыңыз (Атайын мүмкүнчүлүктөр жөндөөлөрү ачылат).",
            "guide_step_2" to "Ал жерден 'Жүктөлгөн кызматтар' же 'Орнотулган тиркемелер' бөлүмүн табыңыз.",
            "guide_step_3" to "Андан кийин 'Qalqon' кызматын таап, аны күйгүзүңүз (ON).",
            "guide_warn" to "💡 Көңүл буруңуз: Бул уруксат аркылуу тиркеме сиз киргизген бөгөттөлгөн домендерди гана текшерет жана эч кандай жеке маалыматтарды топтобойт.",
            "add_new_domain" to "Жаңы Домен Бөгөттөө",
            "add_domain_sub" to "Сайт же оюн топторунун шилтемелерин бөгөттөө",
            "add_btn" to "Киргизүү",
            "spam_list" to "КИРГИЗИЛГЕН СПАМ НОМЕРЛЕР",
            "spam_list_empty" to "Номерлер тизмеси бош.",
            "add_spam_btn" to "Номерди бөгөттөө",
            "import_txt" to "TXT файлдан импорттоо",
            "url_sync" to "URL дарегинен синхрондоштуруу",
            "keywords" to "Ачкыч сөздөр аркылуу чыпкалоо",
            "keywords_desc" to "Ар бир сапка бирден ачкыч сөз киргизесиз (мисалы stavka, 1xbet)",
            "add_keyword" to "Ачкыч сөз кошуу",
            "keyword" to "Ачкыч сөз",
            "registered_keywords" to "КИРГИЗИЛГЕН АЧКЫЧ СӨЗДӨР",
            "admin_only_overlay" to "Бул бөлүм Администратор үчүн гана! Жөндөөлөрдөн 'Администратор Бөлүмүн' иштетиңиз.",
            "select_language" to "🇺🇿 ТИЛ ЖӨНДӨӨЛӨРҮ (LANGUAGE)"
        ),
        AppLanguage.RUSSIAN to mapOf(
            "app_name" to "Калькон",
            "dashboard" to "Главная",
            "protection" to "SMS/Вызовы",
            "monitoring" to "Веб-Фильтр",
            "apk_scan" to "Сканер",
            "settings" to "Настройки",
            "system_protected" to "СИСТЕМА ЗАЩИЩЕНА",
            "security_mode" to "РЕЖИМ БЕЗОПАСНОСТИ",
            "inactive" to "НЕАКТИВЕН",
            "spam_block" to "СПАМ БЛОК",
            "web_filter" to "ВЕБ ФИЛЬТР",
            "spam_desc" to "Запрещенный звонок/sms",
            "domains_desc" to "Заблокированные домены",
            "bg_active" to "Фоновый режим активен и защищает",
            "bg_inactive" to "Защита отключена",
            "recent_activity" to "ПОСЛЕДНИЕ СОБЫТИЯ ЖУРНАЛА",
            "view_all" to "Все >",
            "no_logs" to "Пока нет записей в журнале блокировок.",
            "sms_call_title" to "ФИЛЬТР QALQON",
            "sms_call_sub" to "Управление спам-звонками и SMS",
            "add_spam_num" to "Добавить Спам-Номер",
            "phone_num" to "Номер телефона",
            "num_placeholder" to "Например, +998901234567",
            "label_name" to "Ярлык / Название",
            "label_placeholder" to "Например, Мошенник / Спам",
            "save" to "Сохранить",
            "cancel" to "Отмена",
            "blacklist_web" to "ЧЕРНЫЙ СПИСОК ВЕБ-ФИЛЬТРА",
            "parental_control" to "Родительский контроль: Ограничение доступа к сайтам",
            "add_domain_title" to "Заблокировать Домен",
            "add_domain_desc" to "Например: betting-link.uz. Приложение автоматически блокирует и поддомены.",
            "domain_address" to "Адрес домена",
            "block_reason" to "Причина блокировки",
            "block" to "Блокировать",
            "domain_list_empty" to "Заблокированные сайты отсутствуют.",
            "domain_list_title" to "СПИСОК ЗАБЛОКИРОВАННЫХ ДОМЕНОВ",
            "danger_desc" to "Анализируйте все установленные пакеты. Система сканирует разрешения конфиденциальности.",
            "danger_scanner" to "СКАНЕР ОПАСНЫХ ПРОГРАММ",
            "admin_settings" to "АДМИНИСТРАТИВНЫЕ НАСТРОЙКИ",
            "pin_code" to "PIN Код",
            "wrong_pin" to "Неверный PIN код!",
            "success_login" to "Успешный вход!",
            "admin_locked" to "Раздел Администратора Заблокирован",
            "admin_locked_desc" to "Введите PIN-код администратора для внесения изменений.",
            "enter" to "ВХОД",
            "change_pin" to "Изменить PIN Код",
            "old_pin" to "Старый PIN",
            "new_pin" to "Новый PIN",
            "confirm_pin" to "Подтвердите",
            "pin_update_btn" to "ОБНОВИТЬ ПАРОЛЬ",
            "clear_db" to "Очистить базу данных",
            "clear_db_desc" to "При нажатии этой кнопки спам-лист и веб-фильтры будут очищены и сброшены к заводским.",
            "clear_db_btn" to "СБРОСИТЬ ДАННЫЕ (RESET)",
            "theme_setting" to "🎨 ТЕМА ИНТЕРФЕЙСА (ДЕНЬ / НОЧЬ)",
            "theme_desc" to "Нажмите кнопку ниже, чтобы переключить приложение в светлый (дневной) или темный (ночной) режим.",
            "light_mode_label" to "СВЕТЛЫЙ (ДНЕВНОЙ) РЕЖИМ",
            "dark_mode_label" to "ТЕМНЫЙ (НОЧНОЙ) РЕЖИМ",
            "device_info" to "📱 ИНФОРМАЦИЯ О УСТРОЙСТВЕ",
            "system_label" to "Система:",
            "access_desc" to "Браузерный фильтр",
            "access_on" to "Служба активна",
            "access_off" to "Доступ не предоставлен",
            "enable" to "Включить",
            "fix" to "Исправить",
            "guide_toggle_show" to "+ Открыть инструкцию по активации",
            "guide_toggle_hide" to "- Скрыть инструкцию по активации",
            "guide_title" to "🌐 ИНСТРУКЦИЯ ПО АКТИВАЦИИ ВЕБ-ФИЛЬТРА",
            "guide_step_title" to "Выполните следующие шаги для обнаружения запрещенных сайтов в Google Chrome и других браузерах:",
            "guide_step_1" to "Нажмите 'Включить' в верхнем правом углу (откроются настройки Спец. возможностей).",
            "guide_step_2" to "Найдите раздел 'Скачанные службы' (Downloaded Services) или 'Установленные приложения'.",
            "guide_step_3" to "Выберите службу 'Qalqon' и активируйте ее (Вкл / ON).",
            "guide_warn" to "💡 Внимание: С этим разрешением приложение проверяет только те домены, которые вы заблокировали, и не собирает личные данные.",
            "add_new_domain" to "Заблокировать Новый Домен",
            "add_domain_sub" to "Блокировать ссылки на сайты или игровые группы",
            "add_btn" to "Внести",
            "spam_list" to "СПИСОК ВНЕСЕННЫХ СПАМ-НОМЕРОВ",
            "spam_list_empty" to "Список номеров пуст.",
            "add_spam_btn" to "Заблокировать номер",
            "import_txt" to "Импорт из файла TXT",
            "url_sync" to "Синхронизация из URL",
            "keywords" to "Фильтрация по ключевым словам",
            "keywords_desc" to "Введите по одному ключевому слову в строке (например stavka, 1xbet)",
            "add_keyword" to "Добавить слово",
            "keyword" to "Ключевое слово",
            "registered_keywords" to "ВНЕСЕННЫЕ КЛЮЧЕВЫЕ СЛОВА",
            "admin_only_overlay" to "Этот раздел только для Администратора! Включите 'Раздел Администратора' в настройках.",
            "select_language" to "🇺🇿 ЯЗЫК ПРИЛОЖЕНИЯ (LANGUAGE)"
        ),
        AppLanguage.KARAKALPAK to mapOf(
            "app_name" to "Qalqon",
            "dashboard" to "Baslı",
            "protection" to "SMS/Baylanıs",
            "monitoring" to "Web-Filtr",
            "apk_scan" to "Skaner",
            "settings" to "Sazlawlar",
            "system_protected" to "SISTEMA QORǴALǴAN",
            "security_mode" to "QAWIPSIZLIK REJIMASÍ",
            "inactive" to "BELSENDI EMES",
            "spam_block" to "SPAM BLOK",
            "web_filter" to "WEB FILTR",
            "spam_desc" to "Taqıqlanǵan qońıraw/sms",
            "domains_desc" to "Bloklanǵan domenler",
            "bg_active" to "Fon rejimi belsendi hám qorǵawda",
            "bg_inactive" to "Qorǵaw óshirilgen",
            "recent_activity" to "SOŃǴÍ JURNAL KÓRSETKISHLERI",
            "view_all" to "Barshası >",
            "no_logs" to "Házirshe bloklaw jurnalları joq.",
            "sms_call_title" to "QALQON FILTRI",
            "sms_call_sub" to "SMS hám telefon spam qońırawların basqarıw",
            "add_spam_num" to "Spam Nomer Qosıw",
            "phone_num" to "Telefon nomeri",
            "num_placeholder" to "Dıqqat, +998901234567",
            "label_name" to "Belgi / Atı",
            "label_placeholder" to "Mısalı, Aldawshı / Spam",
            "save" to "Saqlaw",
            "cancel" to "Biykarlaw",
            "blacklist_web" to "QORALIST WEB-FILTR",
            "parental_control" to "Parental-control: Taqıqlanǵan saytlarǵa kiriwdi sheklew",
            "add_domain_title" to "Taqıqlanǵan Domen Qosıw",
            "add_domain_desc" to "Mısalı: betting-link.uz. Programma subdomenlerdi de avtomat bloklaydı.",
            "domain_address" to "Domen adresi",
            "block_reason" to "Bloklaw sebebi",
            "block" to "Bloklaw",
            "domain_list_empty" to "Bloklanǵan saytlar joq.",
            "domain_list_title" to "BLOKLANǴAN DOMENLER RO'YXATI",
            "danger_desc" to "Barlıq ornatılǵan paketlerdi talqılań. Sistema jeke ruxsatnamalardı skanerleydi.",
            "danger_scanner" to "QAWIPLI PROGRAMMALAR SKANERI",
            "admin_settings" to "BASHQARÍW SAZLAWLARÍ",
            "pin_code" to "PIN Kod",
            "wrong_pin" to "PIN kod qáte!",
            "success_login" to "Muvaffaqiyatlı kirildi!",
            "admin_locked" to "Administrator Bólisi Qulıplanǵan",
            "admin_locked_desc" to "Ózgerisler qosıw ushın administrator PIN-kodın kiritiń.",
            "enter" to "KIRIW",
            "change_pin" to "PIN Kodtı ózgertiw",
            "old_pin" to "Eski PIN",
            "new_pin" to "Jaña PIN",
            "confirm_pin" to "Tastıyıqlań",
            "pin_update_btn" to "PAROLDÍ JAŃALAW",
            "clear_db" to "Dárekler bazasın tazalaw",
            "clear_db_desc" to "Bul túyme basılǵanda spam tizi hám web filtrler óshiriledi hám baslangısh qalpına qaytarıladı.",
            "clear_db_btn" to "MAL'UMOTLARDÍ TAZALAW (RESET)",
            "theme_setting" to "🎨 INTERFEYS MAVZUSÍ (KÚN / TUN)",
            "theme_desc" to "Ilovanı aq (kúndizgi) yamasa qara (túngi) rejimde isletiw ushın túymeni basıń.",
            "light_mode_label" to "KÚNDIZGI (AQ) REJIM",
            "dark_mode_label" to "TÚNGI (QARA) REJIM",
            "device_info" to "📱 QURÍLMA MAL'UMOTLARÍ",
            "system_label" to "Tizim:",
            "access_desc" to "Brauzer filtri",
            "access_on" to "Xızmet belsendi",
            "access_off" to "Arnawlı ruxsat berilmegen",
            "enable" to "Yoqısh",
            "fix" to "Túzetiw",
            "guide_toggle_show" to "+ Aktivlestiriw kórsetpesin ashıw",
            "guide_toggle_hide" to "- Aktivlestiriw kórsetpesin jabıw",
            "guide_title" to "🌐 BRAUZER FILTRIN ISKE QOSÍW KÓRSETPESI",
            "guide_step_title" to "Google Chrome hám basqa brauzerlerde taqıqlanǵan saytlardı anıqlaw ushın quyıdaǵı qádemlerdi orınlań:",
            "guide_step_1" to "Joqarı oń jaqtaǵı 'Yoqısh' túymesin basıń (Sistemanıń maxsus emkaniyatlar sazlawları ashıladı).",
            "guide_step_2" to "Sodan 'Júklep alınǵan xızmetler' yamasa 'Ornatılǵan programmalar' bólimin tabıń.",
            "guide_step_3" to "Sol jerden 'Qalqon' xızmetine basıp, onı aktivlestiriń (Yoqısh / ON).",
            "guide_warn" to "💡 Diqqat: Bul ruxsatnama arqalı programma tek siz kirgizgen blok-domenlerdi tekseredi hám jeke dáreklerdi jıynamaydı.",
            "add_new_domain" to "Jaña Domen Bloklaw",
            "add_domain_sub" to "Sayt yamasa oyın toparları siltemelerin bloklaw",
            "add_btn" to "Kiritish",
            "spam_list" to "KIRGIZILGEN SPAM NOMERLER",
            "spam_list_empty" to "Nomerler tizi bos.",
            "add_spam_btn" to "Nomerdi bloklaw",
            "import_txt" to "TXT fayldan import qılıw",
            "url_sync" to "URL adresten sinxronlaw",
            "keywords" to "Kilt sózler arqalı filtrlew",
            "keywords_desc" to "Hár bir qatarda bir kilt sóz kirgizesiz (mısalı stavka, 1xbet)",
            "add_keyword" to "Kilt sóz qosıw",
            "keyword" to "Kilt sóz",
            "registered_keywords" to "KIRGIZILGEN KILT SÓZLER",
            "admin_only_overlay" to "Bul bólim tek Administrator ushın! Sazlawlardan 'Administrator Bólimin' belsendi qılıń.",
            "select_language" to "🇺🇿 BAǴDARLAMA TILI (LANGUAGE)"
        ),
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "Qalqon",
            "dashboard" to "Dashboard",
            "protection" to "SMS/Call",
            "monitoring" to "Web-Filter",
            "apk_scan" to "Scanner",
            "settings" to "Settings",
            "system_protected" to "SYSTEM PROTECTED",
            "security_mode" to "SECURITY MODE",
            "inactive" to "INACTIVE",
            "spam_block" to "SPAM BLOCK",
            "web_filter" to "WEB FILTER",
            "spam_desc" to "Forbidden calls & SMS",
            "domains_desc" to "Blocked domains",
            "bg_active" to "Background guard is active and watching",
            "bg_inactive" to "Protection is disabled",
            "recent_activity" to "RECENT BLOCK LOGS",
            "view_all" to "View All >",
            "no_logs" to "No block events captured yet.",
            "sms_call_title" to "QALQON FILTER",
            "sms_call_sub" to "Manage incoming call and SMS protections",
            "add_spam_num" to "Add Spam Number",
            "phone_num" to "Phone number",
            "num_placeholder" to "e.g. +998901234567",
            "label_name" to "Label / Sender Name",
            "label_placeholder" to "e.g. Scammer / Robocall",
            "save" to "Save",
            "cancel" to "Cancel",
            "blacklist_web" to "WEB-FILTER BLACKLIST",
            "parental_control" to "Parental-control: Restrict unsafe web links",
            "add_domain_title" to "Block Unsafe Domain",
            "add_domain_desc" to "e.g. betting-link.uz. App blocks subdomains dynamically as well.",
            "domain_address" to "Domain URL address",
            "block_reason" to "Block reason",
            "block" to "Block",
            "domain_list_empty" to "No blocked websites registered.",
            "domain_list_title" to "BLOCKED DOMAINS REGISTRY",
            "danger_desc" to "Audit installed application packages. Skan privacy risks and dangerous permissions.",
            "danger_scanner" to "MALWARE & PRIVACY SCANNER",
            "admin_settings" to "ADMINISTRATIVE CONTROL PANEL",
            "pin_code" to "PIN Code",
            "wrong_pin" to "Incorrect PIN code!",
            "success_login" to "Access granted successfully!",
            "admin_locked" to "Administrator Panel Locked",
            "admin_locked_desc" to "Enter administrator PIN-code to perform secure modifications.",
            "enter" to "UNLOCK",
            "change_pin" to "Change PIN Code",
            "old_pin" to "Current PIN",
            "new_pin" to "New PIN",
            "confirm_pin" to "Verify PIN",
            "pin_update_btn" to "UPDATE PASSCODE",
            "clear_db" to "Purge Local Database",
            "clear_db_desc" to "Wipe all current blocked numbers, domains, keywords and reset to factory defaults.",
            "clear_db_btn" to "RESET APPLICATION (DELETE ALL)",
            "theme_setting" to "🎨 DISPLAY LIGHT / DARK MODE",
            "theme_desc" to "Toggle light (daytime) or dark (nighttime) background look globally.",
            "light_mode_label" to "LIGHT (DAY) MODE",
            "dark_mode_label" to "DARK (NIGHT) MODE",
            "device_info" to "📱 HARDWARE SPECIFICATIONS",
            "system_label" to "System Engine:",
            "access_desc" to "Browser Accessibility Guard",
            "access_on" to "Active and Vigilant",
            "access_off" to "Disabled / No rights",
            "enable" to "Enable",
            "fix" to "Configure",
            "guide_toggle_show" to "+ Open activation handbook step guide",
            "guide_toggle_hide" to "- Close activation handbook step guide",
            "guide_title" to "🌐 WEB BROWSER FILTER ACTIVATION BOOK",
            "guide_step_title" to "Perform these 3 sequential steps to intercept blocked casinos and betting sites in Chrome:",
            "guide_step_1" to "Click the top-right 'Enable' or 'Configure' button to open Accessibility settings.",
            "guide_step_2" to "Locate the 'Downloaded Services' or 'Installed Apps' category.",
            "guide_step_3" to "Select 'Qalqon' service and shift the slider switch to ON/ENABLE.",
            "guide_warn" to "💡 Note: Using this permission, Qalqon only tests current URL against list and never records private text or data.",
            "add_new_domain" to "Register Block Domain",
            "add_domain_sub" to "Configure blocks for gambling, casino, betting & social links",
            "add_btn" to "Register",
            "spam_list" to "BLOCKED SPAM PHONE REGISTRY",
            "spam_list_empty" to "Phone block registry is empty.",
            "add_spam_btn" to "Register Number Blacklist",
            "import_txt" to "Bulk CSV/TXT File Import",
            "url_sync" to "Sync from Remote Control URL",
            "keywords" to "Keyword Content Blocking",
            "keywords_desc" to "Enter one trigger spam keyword per line (e.g. betting, prize, lottery)",
            "add_keyword" to "Add Keyword",
            "keyword" to "Keyword",
            "registered_keywords" to "BLOCKED KEYWORDS LIST",
            "admin_only_overlay" to "This section is restricted to Administrators! Please unlock the Administrator section from Settings.",
            "select_language" to "🇺🇿 CHANGE APPLICATION LANGUAGE"
        )
    )

    fun getString(lang: AppLanguage, key: String): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.UZ_LATIN]?.get(key) ?: key
    }
}
